src/apps/inventory/urls.py
from django.urls import path
from apps.inventory.views import AssignmentListAjaxView, AssignmentListView, AssignmentStudentCreateView, AssignmentUpdateView, ComputerCreateView, CourseCreateView, CourseListView, CourseUpdateView, MatterCreateView, MatterListFilterView, MatterListView, MatterUpdateView, PersonListFilterView, ToggleAvailabilityView
from apps.inventory.views import ComputerListView
from apps.inventory.views import ComputerDeleteView
from apps.inventory.views import ComputerUpdateView
from apps.inventory.views import AssignmentCreateView

from apps.inventory.views import PersonCreateView
from apps.inventory.views import PersonListView
from apps.inventory.views import PersonDeleteView
from apps.inventory.views import PersonUpdateView


app_name = 'inventory'

urlpatterns = [
    path('computer/create/', ComputerCreateView.as_view(), name='create-computer'),
    path('computer/list/', ComputerListView.as_view(), name='list-computer'),
    path('computer/delete/<int:pk>', ComputerDeleteView.as_view(), name='delete-computer'),
    path('computer/update/<int:pk>', ComputerUpdateView.as_view(), name='update-computer'),
    
    path('person/create/', PersonCreateView.as_view(), name='create-person'),
    path('person/list/', PersonListView.as_view(), name='list-person'),
    path('person/delete/<int:pk>', PersonDeleteView.as_view(), name='delete-person'),
    path('person/update/<int:pk>', PersonUpdateView.as_view(), name='update-person'),
    path('person/search/', PersonListFilterView.as_view(), name='filter-person'),
    
    
    path('assignment/create/', AssignmentCreateView.as_view(), name='create-assignment'),
    path('assignment/list/', AssignmentListView.as_view(), name='list-assignment'),
    path('assignments/ajax/', AssignmentListAjaxView.as_view(), name='assignment_list_ajax'),
    path('assignment/update/<int:pk>',  AssignmentUpdateView.as_view(), name='update-assignment'),
    path('computer/<int:pk>/toggle/', ToggleAvailabilityView.as_view(), name='toggle-availability'),
    path('assignment/student/create/', AssignmentStudentCreateView.as_view(), name='create-assignment-student'),

    path('course/create/', CourseCreateView.as_view(), name='create-course'),
    path('course/list/', CourseListView.as_view(), name='list-course'),
    path('course/update/<int:pk>',  CourseUpdateView.as_view(), name='update-course'),

    path('matter/create/', MatterCreateView.as_view(), name='create-matter'),
    path('matter/list/', MatterListView.as_view(), name='list-matter'),
    path('matter/update/<int:pk>',  MatterUpdateView.as_view(), name='update-matter'),
    path('matter/search/', MatterListFilterView.as_view(), name='filter-matter'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from apps.security.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.inventory.urls')),
    path('home/', include('apps.home.urls', namespace='home')),
    
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

src/apps/inventory/models.py
from datetime import timedelta
from django.db import models
from django.utils import timezone

class Computer(models.Model):
    number = models.PositiveIntegerField(unique=True)
    first_name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    is_available = models.BooleanField(default=True)
    is_technical_issue = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"PC #{self.number}"

class Person(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dni = models.PositiveIntegerField(unique=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
     
class Course(models.Model):
    first_name = models.CharField(max_length=100) 
    is_deleted = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.first_name} {self.first_name}" 

class Matter(models.Model):
    first_name = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="matters")
    is_deleted = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.first_name} ({self.course.first_name})"
    
class Assignment(models.Model):
    computer = models.ForeignKey(Computer, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    requested_at = models.DateTimeField(auto_now_add=True)
    returned_at = models.DateTimeField(null=True, blank=True)
    observation = models.CharField(max_length=255, default='Sin observaciones')
    returned = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-requested_at'] 

    def __str__(self):
        return f"{self.person} - PC #{self.computer.number}"

    @property
    def is_alert(self):
        """Retorna True si pasaron más de 2 horas sin devolución"""
        if not self.returned:
            return timezone.now() > self.requested_at + timedelta(hours=2)
        return False

src/templates/person/create.html
{% extends 'home/home.html' %}

{% block section %}


<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-lg border-0">
        <div class="card-header bg-primary text-white">
          <h3 class="card-title mb-0">Registrar Estudiante</h3>
        </div>
        <form method="post" enctype="multipart/form-data" class="p-4">
          {% csrf_token %}

          <div class="form-outline">
            <input type="text" name="first_name" maxlength="100" required id="id_first_name" placeholder=" " />
            <label for="id_first_name">Nombre<span class="required-asterisk">*</span></label>
          </div>

          <div class="form-outline">
            <input type="text" name="last_name" maxlength="100" required id="id_last_name" placeholder=" " />
            <label for="id_last_name">Apellido<span class="required-asterisk">*</span></label>
          </div>

          <div class="form-outline">
            <input type="text" name="dni" maxlength="8" required id="id_dni" placeholder=" " />
            <label for="id_dni">DNI<span class="required-asterisk">*</span></label>
          </div>

          <div class="d-grid">
            <button type="submit" class="btn btn-primary">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/templates/person/delete.html
<h2>¿Estás seguro que deseas eliminar la computadora?</h2>
<form method="post">
  {% csrf_token %}
  <button type="submit">Sí, eliminar</button>
  <a href="{% url 'inventory:list-computer' %}">Cancelar</a>
</form>

src/templates/person/list.html
{% extends "home/home.html" %}

{% block section %}
{% include 'include/messages.html' %}

<section class="container py-4">

  <!-- Cabecera y botón Agregar -->
  <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-around align-items-center">
                <h2 class="card-title">Estudiantes</h2>
                <a href="{% url 'inventory:create-person' %}" class="btn btn-primary btn-sm">                        
                    <i class="fas fa-plus">
                    </i>
                        Agregar
                </a>
            </div>
           
        </div>
    </div>

<!-- Formulario de búsqueda -->
  <form method="get"  action="{% url 'inventory:filter-person' %}" class="input-group mb-4">
    <input type="text" name="search" value="{{ request.GET.search }}" class="form-control" placeholder="Buscar estudiante...">
    <button class="btn btn-outline-primary" type="submit">
      <i class="fas fa-search"></i>
    </button>
  </form>

  <!-- Tabla de estudiantes -->
  <div class="card shadow-sm">
    <div class="card-body p-0">
      <div class="table-responsive">
        <table class="table table-striped table-hover align-middle text-nowrap mb-0">
          <thead class="bg-primary text-white">
            <tr>
              <th style="width: 20%;">Nombre</th>
              <th style="width: 30%;">Apellido</th>
              <th style="width: 30%;">DNI</th>
              <th style="width: 20%;">Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for person in persons %}
              <tr>
                <td>{{ person.first_name }}</td>
                <td>{{ person.last_name }}</td>
                <td>{{ person.dni }}</td>
                <td class="text-end">
                  <div class="btn-group btn-group-sm">
                    <a href="{% url 'inventory:update-person' person.id %}" class="btn btn-outline-primary" title="Editar">
                      <i class="fas fa-pencil-alt"></i>
                    </a>
                    <a href="{% url 'inventory:delete-person' person.id %}" class="btn btn-outline-danger" title="Eliminar">
                      <i class="fas fa-trash"></i>
                    </a>
                  </div>
                </td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="4" class="text-center py-4">No se encontraron estudiantes.</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <!-- Paginación -->
    <div class="card-footer">
      <ul class="pagination pagination-sm m-0 justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">&laquo;</span>
          </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <li class="page-item active">
              <span class="page-link">{{ num }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">&raquo;</span>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>

</section>
{% endblock %}

src/templates/person/update.html
{% extends 'home/home.html' %}

{% block section %}
<div class="container-fluid">
  <div class="row justify-content-center">    
    <div class="col-md-6"> 
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Actualizar Estudiante</h3>
        </div>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card-body">
            <div class="form-group">
              <label for="id_first_name">Nombre</label>
              <input type="text" name="first_name"  value="{{ persons.first_name }}" maxlength="100" required class="form-control" id="id_first_name">
            </div>
            <div class="form-group">
              <label for="id_last_name">Apellido</label>
              <input type="text" name="last_name" value="{{ persons.last_name }}" maxlength="100" required class="form-control" id="id_last_name">
            </div>
            <div class="form-group">
              <label for="id_dni">DNI</label>
              <input type="number" name="dni" value="{{ persons.dni }}"required class="form-control" id="id_dni">
            </div>
           
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Actualizar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}