src/apps/home/urls.py
# En tu archivo apps/home/urls.py
from django.urls import path
from .views import IndexView

app_name = 'home'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

src/apps/inventory/urls.py
from django.urls import path
from apps.inventory.views import AssignmentListAjaxView, AssignmentListView, AssignmentStudentCreateView, AssignmentUpdateView, ComputerCreateView, CourseCreateView, CourseListView, CourseUpdateView, MatterCreateView, MatterListFilterView, MatterListView, MatterUpdateView, PersonListFilterView, ToggleAvailabilityView
from apps.inventory.views import ComputerListView
from apps.inventory.views import ComputerDeleteView
from apps.inventory.views import ComputerUpdateView
from apps.inventory.views import AssignmentCreateView

from apps.inventory.views import PersonCreateView
from apps.inventory.views import PersonListView
from apps.inventory.views import PersonDeleteView
from apps.inventory.views import PersonUpdateView


app_name = 'inventory'

urlpatterns = [
    path('computer/create/', ComputerCreateView.as_view(), name='create-computer'),
    path('computer/list/', ComputerListView.as_view(), name='list-computer'),
    path('computer/delete/<int:pk>', ComputerDeleteView.as_view(), name='delete-computer'),
    path('computer/update/<int:pk>', ComputerUpdateView.as_view(), name='update-computer'),
    
    path('person/create/', PersonCreateView.as_view(), name='create-person'),
    path('person/list/', PersonListView.as_view(), name='list-person'),
    path('person/delete/<int:pk>', PersonDeleteView.as_view(), name='delete-person'),
    path('person/update/<int:pk>', PersonUpdateView.as_view(), name='update-person'),
    path('person/search/', PersonListFilterView.as_view(), name='filter-person'),
    
    
    path('assignment/create/', AssignmentCreateView.as_view(), name='create-assignment'),
    path('assignment/list/', AssignmentListView.as_view(), name='list-assignment'),
    path('assignments/ajax/', AssignmentListAjaxView.as_view(), name='assignment_list_ajax'),
    path('assignment/update/<int:pk>',  AssignmentUpdateView.as_view(), name='update-assignment'),
    path('computer/<int:pk>/toggle/', ToggleAvailabilityView.as_view(), name='toggle-availability'),
    path('assignment/student/create/', AssignmentStudentCreateView.as_view(), name='create-assignment-student'),

    path('course/create/', CourseCreateView.as_view(), name='create-course'),
    path('course/list/', CourseListView.as_view(), name='list-course'),
    path('course/update/<int:pk>',  CourseUpdateView.as_view(), name='update-course'),

    path('matter/create/', MatterCreateView.as_view(), name='create-matter'),
    path('matter/list/', MatterListView.as_view(), name='list-matter'),
    path('matter/update/<int:pk>',  MatterUpdateView.as_view(), name='update-matter'),
    path('matter/search/', MatterListFilterView.as_view(), name='filter-matter'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from apps.security.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.inventory.urls')),
    path('home/', include('apps.home.urls', namespace='home')),
    
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

src/apps/home/models.py
from django.db import models

# Create your models here.

src/apps/home/views.py
from typing import Any
from django import http
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from apps.inventory.models import Assignment, Computer, Course, Matter, Person
# Create your views here.

class IndexView(LoginRequiredMixin,TemplateView):
    template_name = 'home/index.html' 
    
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            computers = Computer.objects.filter(is_deleted=False)
            total_computers = computers.count()
            context['total_computers'] = total_computers
            
            assignments = Assignment.objects.filter(is_deleted=False)
            total_assignments = assignments.count()
            context['total_assignments'] = total_assignments
            
            person = Person.objects.filter(is_deleted=False)
            total_person = person.count()
            context['total_persons'] = total_person
        
            course = Course.objects.filter(is_deleted=False)
            total_course = course.count()
            context['total_courses'] = total_course
            
        
            matter = Matter.objects.filter(is_deleted=False)
            total_matter = matter.count()
            context['total_matters'] = total_matter
            return context


 

src/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CTP-PAÑOL</title>

  <link rel="shortcut icon" href="https://ctpantoniomarte.edu.ar/wp-content/uploads/2024/08/cropped-logo-marte.png" type="image/x-icon">

  <!-- Google Font: Source Sans Pro -->  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href = "{% static 'lib/AdminLTE-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href = "{% static 'lib/AdminLTE-3.2.0/css/adminlte.min.css' %}">
  <link rel="stylesheet" href = "{% static 'lib/AdminLTE-3.2.0/plugins/ekko-lightbox/ekko-lightbox.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Roboto:wght@400;500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href = "{% static 'inventory/css/style.css' %}">
  <link rel="stylesheet" href = "{% static 'css/style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body class="hold-transition bg-light">

<div class="scrollable-container">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item">
        <a class="navbar-brand text" href="{% url 'home:index' %}">Inicio</a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <form method="post" action="{% url 'logout' %}" style="display:inline;">
          {% csrf_token %}
          <button class="nav-link btn btn-link p-0" type="submit" role="button" title="Cerrar sesión">
            <i class="fas fa-sign-out-alt fa-lg"></i>
          </button>
        </form>
      </li>    
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-purple elevation-4">
    <!-- Brand Logo -->
    <a href="/home" class="brand-link">
        <img src = "https://ctpantoniomarte.edu.ar/wp-content/uploads/2024/08/cropped-logo-marte.png"  alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
          <span class="brand-text font-weight-light">          
            Antonio Marte
          </span>
    </a>
   
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src = 'https://cdn.pixabay.com/photo/2017/07/18/23/23/user-2517433_640.png' class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ user.username }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-header">GESTIÓN</li>
         <li class="nav-item">
  <a href="{% url 'inventory:list-person' %}" class="nav-link d-flex justify-content-between align-items-center">
    <div>
      <i class="fas fa-users fa-fw"></i>
      <span class="ml-2">Estudiantes</span>
    </div>
    <span class="badge badge-info">{{ total_person }}</span>
  </a>
</li>
          <li class="nav-item">
            <a  class="nav-link" href="{% url 'inventory:list-course'%}">
              <i class="nav-icon fas fa-graduation-cap"></i>
              <p>
                Curso 
              </p>
            </a>         
          </li>
          <li class="nav-item">
            <a  class="nav-link" href="{% url 'inventory:list-matter'%}" >
              <i class="nav-icon fas fa-book-reader"></i>
              <p>
                Materias
              </p>
            </a>         
          </li>
          <li class="nav-item">
            <a  class="nav-link" href="{% url 'inventory:list-computer'%}">
              <i class="nav-icon fas fa-desktop" ></i>
              <p>
                  Computadoras
              </p>
            </a>         
          </li>
         
          <li class="nav-item">
            <a  class="nav-link" href="{% url 'inventory:list-assignment'%}">
              <i class="nav-icon fas fa-exchange"></i>
              <p>
                Reservas 
              </p>
            </a>         
          </li>
        </li>   
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <br>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            
            {% block section %}
          
            {% endblock section %} 
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2019-2025 </strong>C.T.P.A.M.M.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>


<!-- jQuery -->
<script src = "{% static 'lib/AdminLTE-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script   src = "{% static 'lib/AdminLTE-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src = "{% static 'lib/AdminLTE-3.2.0/js/adminlte.min.js' %}" ></script>
<script src = "{% static 'js/inputFile.js' %}" ></script>
<!-- AdminLTE for demo purposes -->
<script src = "{% static 'lib/AdminLTE-3.2.0/plugins/filterizr/jquery.filterizr.min.js' %}" ></script>
<script src = "{% static 'lib/AdminLTE-3.2.0/plugins/ekko-lightbox/ekko-lightbox.min.js' %}" ></script>
</div>
{% block script %}

{% endblock script %}
</body>
</html>

src/templates/home/index.html
{% extends "home/home.html" %}

{% block section %}
{% include 'include/messages_login.html' %}

<div class="container py-4">
  <div class="row gx-5 gy-5 justify-content-center">

    <!-- Card Estudiantes -->
    <div class="col-12 col-md-6 col-lg-4">
      <a href="{% url 'inventory:list-person' %}" class="text-decoration-none text-dark">
        <div class="card shadow rounded h-100 hover-shadow p-4 position-relative">
          <div class="d-flex align-items-center">
            <i class="fas fa-users fa-3x text-primary me-3"></i>
            <div>
              <h5 class="card-title mb-1">Estudiantes</h5>
              <p class="card-text text-muted mb-0">Total de estudiantes</p>
            </div>
          </div>
          <span class="badge bg-danger position-absolute top-0 end-0 m-3 fs-6">
            {{ total_persons }}
          </span>
        </div>
      </a>
    </div>

    <!-- Card Cursos -->
    <div class="col-12 col-md-6 col-lg-4">
      <a href="{% url 'inventory:list-course' %}" class="text-decoration-none text-dark">
        <div class="card shadow rounded h-100 hover-shadow p-4 position-relative">
          <div class="d-flex align-items-center">
            <i class="fas fa-chalkboard-teacher fa-3x text-success me-3"></i>
            <div>
              <h5 class="card-title mb-1">Cursos</h5>
              <p class="card-text text-muted mb-0">Total de cursos</p>
            </div>
          </div>
          <span class="badge bg-danger position-absolute top-0 end-0 m-3 fs-6">
            {{ total_courses }}
          </span>
        </div>
      </a>
    </div>

    <!-- Card Materias -->
    <div class="col-12 col-md-6 col-lg-4">
      <a href="{% url 'inventory:list-matter' %}" class="text-decoration-none text-dark">
        <div class="card shadow rounded h-100 hover-shadow p-4 position-relative">
          <div class="d-flex align-items-center">
            <i class="fas fa-book fa-3x text-warning me-3"></i>
            <div>
              <h5 class="card-title mb-1">Materias</h5>
              <p class="card-text text-muted mb-0">Total de materias</p>
            </div>
          </div>
          <span class="badge bg-danger position-absolute top-0 end-0 m-3 fs-6">
            {{ total_matters }}
          </span>
        </div>
      </a>
    </div>

    <!-- Card Computadoras -->
    <div class="col-12 col-md-6 col-lg-4">
      <a href="{% url 'inventory:list-computer' %}" class="text-decoration-none text-dark">
        <div class="card shadow rounded h-100 hover-shadow p-4 position-relative">
          <div class="d-flex align-items-center">
            <i class="fas fa-desktop fa-3x text-info me-3"></i>
            <div>
              <h5 class="card-title mb-1">Computadoras</h5>
              <p class="card-text text-muted mb-0">Total de computadoras</p>
            </div>
          </div>
          <span class="badge bg-danger position-absolute top-0 end-0 m-3 fs-6">
            {{ total_computers }}
          </span>
        </div>
      </a>
    </div>

    <!-- Card Reservas -->
    <div class="col-12 col-md-6 col-lg-4">
      <a href="{% url 'inventory:list-assignment' %}" class="text-decoration-none text-dark">
        <div class="card shadow rounded h-100 hover-shadow p-4 position-relative">
          <div class="d-flex align-items-center">
            <i class="fas fa-exchange-alt fa-3x text-danger me-3"></i>
            <div>
              <h5 class="card-title mb-1">Reservas</h5>
              <p class="card-text text-muted mb-0">Total de reservas</p>
            </div>
          </div>
          <span class="badge bg-danger position-absolute top-0 end-0 m-3 fs-6">
            {{ total_assignments }}
          </span>
        </div>
      </a>
    </div>

  </div>
</div>

<style>
  /* Sombra hover para las cards */
  .hover-shadow:hover {
    box-shadow: 0 0.75rem 1.5rem rgba(0, 0, 0, 0.2);
    transform: translateY(-4px);
    transition: all 0.3s ease;
  }
</style>

{% endblock %}